version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: task_manager_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task_manager_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_manager_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/vendor:/var/www/vendor
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: task_manager
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - task_manager_network
    command: >
      sh -c "composer install &&
             php artisan key:generate &&
             php artisan migrate --force &&
             php artisan db:seed --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  # Vue Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_manager_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - task_manager_network
    command: npm run dev -- --host

  # phpMyAdmin - Database Admin Interface
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: task_manager_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - task_manager_network

volumes:
  mysql_data:
    driver: local

networks:
  task_manager_network:
    driver: bridge